id: P003228
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:52.348731
source_metadata:
  id: bdr:W00KG03151
  title: བྲག་གཡབ་ཆེ་བཟང་བློ་བཟང་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    33a8808855e24a26a9fda44c0adcbd2d:
      image_group_id: I00KG03153
      title: ''
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
